implement native multisend
Taraxa-project/tara-erc20 pull request #4
Opened 2023-03-23 19:40 UTC by VargaElod23

2023-03-27 14:13 UTC, rattrap requested changes

2023-03-27 14:13 UTC, rattrap commented on contracts/MultisendNative.sol
> +        return (i, total);
Don't need to return anything

2023-03-27 14:13 UTC, rattrap commented on contracts/MultisendNative.sol
> +                break;
Too complicated and doesn't cover the case where we send this function more tokens than in the amounts array.

Let's just break here and move the send back functionality after the for

2023-03-27 14:13 UTC, rattrap commented on test/MultisendNative.test.js
> +  });
I think we can merge this with the previous test

2023-03-27 16:16 UTC, VargaElod23 commented on test/MultisendNative.test.js
> +  });
I would like to keep these two as separate scenarios

2023-04-12 07:58 UTC, VargaElod23 commented
- [x] Removed fallback receiver

2023-04-13 12:20 UTC, rattrap requested changes

2023-04-13 12:20 UTC, rattrap commented on contracts/MultisendNative.sol
> +                total = total + _amounts[i];
Let's also add an event that contains address and amount

2023-04-13 12:20 UTC, rattrap commented on contracts/MultisendNative.sol
> +        emit TokensSent(i, total);
We can just remove this

2023-04-13 12:20 UTC, rattrap commented on contracts/MultisendNative.sol
> +            if ((msg.value - total) >= _amounts[i]) {
Maybe we can reorganize this a bit - https://github.com/Alonski/MultiSendEthereum/blob/master/contracts/MultiSend.sol#L89

2023-04-18 11:25 UTC, rattrap approved these changes

2023-04-18 11:25 UTC, merged